#!/bin/bash

POKEMON_API_URL="https://pokeapi.co/api/v2/pokemon"
ERROR_LOG="errors.txt"
DATA_DIR="pokemon_data"
DEFAULT_DELAY=5

setup_utils() {
    if [ -f $ERROR_LOG ]; then
        rm $ERROR_LOG
    fi

    if [ ! -d $DATA_DIR ]; then
        mkdir -p $DATA_DIR
    fi
}

request_pokemon() {
    echo "Fetching data for $1..."
    curl -s "${POKEMON_API_URL}/${1}" > "${DATA_DIR}/${1}.json" 2>> $ERROR_LOG

    if [ $? -ne 0 ]; then
        echo "Error occurred while fetching data for $1, check $ERROR_LOG for the error logs."
    else
        echo "Saved data to ${DATA_DIR}/${1}.json ✅"
    fi
}

main() {
    echo "Setting up utils ..."
    setup_utils

    array=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
    for name in ${array[@]}; do
        request_pokemon $name
        sleep $DEFAULT_DELAY
    done
}

main
echo "All requests completed."
